name: Build EXE
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyinstaller requests pyrogram
      - run: pyinstaller --onefile --noconsole --name DynKill 1.py
      - uses: actions/upload-artifact@v4
        with:
          name: executable
          path: dist/DynKill.exe
